name: techub
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.7.0
  flutter_svg: ^1.1.6
  logger: ^1.3.0
  fluttertoast: ^8.2.2
  dio: ^5.2.1
  freezed_annotation: ^2.2.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.14
  freezed: ^2.4.2
  json_annotation: ^4.8.1
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_annotation: ^4.8.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - .env
   - asset/image/

  fonts:
   - family: Pretendard
     fonts:
       - asset: asset/font/pretendard-variable.ttf

